### ISSUE TITLE
TeamTreehouse Code Louisville FEWD Class

### ISSUE THREAD

**Issue by byshieldmaiden** [byshieldmaiden/treehouse#2]
## TODO

*Courses left to complete in this track*

* [] Github Basics
* [] HTML Video and Audio
* [] Responsive Layouts
* [] AJAX Basics
* [] Object Oriented JavaScript
* [] Accessibility
* [] Website Optimization
* [] Front End Performance Optimization
* [] Introduction to Design Patterns
* [] Framework Basics

💯  :bowtie: 🎉
